recruit-tech/redux-pluto

- src/server/middlewares/reduxApp.js
SSRで返すHTMLドキュメントに`Content-Type`がついてなかったのでつけました
> fix: add content-type text/html

- package.json
webpack 系のモジュールはすでに最新になっているようなので、greenkeeper の ignore から外すという変更です。
eslint-config-airbnb と flow-bin は上げると lint error / type error が出るようだったのでそのままにしています。
> Remove modules from greenkeeper's ignore list

- spec/agreed/agreed.js
- spec/agreed/agreedsample/400_get.json5
- spec/agreed/agreedsample/404_get.json5
- spec/agreed/agreedsample/500_get.json5
- src/server/middlewares/reduxApp.js
- src/server/services/AgreedSample.js
- src/server/services/utils.js
- src/shared/components/organisms/AgreedSample/index.js
- src/shared/redux/middleware/apiErrorMiddleware.js
- src/shared/redux/modules/agreedSample.js
kani さんからの指摘で SSR 実行中のprefetch時にエラーが走るとすべて500のエラーとなる現象を解消した。
実際には 400系は apiErrorMiddleware でエラー発生時にmodalを出し、その上でrenderさせている。 500系の時は落ちたのと同等扱い。
see:
localhost:3000/agreedsample?status=400
> fix: render SSR when prefetch response code is 400

- src/shared/components/organisms/Login/LoginForm.js
ssr を skip させるのを以前は chrome のバグが元で実装していたが、既に修正されたようなのでskipSSRは削除。
> fix: remove skipssr on login

- src/server/services/__tests__/AccessToken.create.test.js
- src/server/services/__tests__/AccessToken.delete.test.js
- src/server/services/__tests__/AgreedSample.read.test.js
- src/server/uploaders/__tests__/UploadSample.test.js
- src/shared/components/atoms/__tests__/Indicator.test.js
- src/shared/components/atoms/__tests__/Menu.test.js
- src/shared/components/atoms/__tests__/MenuItem.test.js
- src/shared/components/atoms/__tests__/Overlay.test.js
- src/shared/components/atoms/__tests__/SearchListItem.test.js
- src/shared/components/atoms/__tests__/SearchMore.test.js
- src/shared/redux/__tests__/agreedSample.test.js
- src/shared/redux/__tests__/auth.checkLogin.test.js
- src/shared/redux/__tests__/auth.login.test.js
- src/shared/redux/__tests__/auth.logout.test.js
- src/shared/redux/__tests__/counter.test.js
- src/shared/redux/__tests__/hackerNews.test.js
- src/shared/redux/__tests__/master.areaMaster.test.js
- src/shared/redux/__tests__/master.genderMaster.test.js
- src/shared/redux/__tests__/master.hairColorMaster.js
- src/shared/redux/__tests__/master.hairLengthMaster.test.js
- src/shared/redux/__tests__/master.loadMaster.test.js
- src/shared/redux/__tests__/master.menuContentMaster.test.js
- src/shared/redux/__tests__/search.test.js
- src/shared/redux/__tests__/searchList.test.js
- src/shared/redux/__tests__/style.searchStyle.test.js
- src/shared/redux/__tests__/uploadSample.test.js
- src/shared/redux/modules/__tests__/alert.test.js
- src/shared/redux/modules/__tests__/auth.test.js
- src/shared/redux/modules/__tests__/loading.test.js
- src/shared/redux/modules/__tests__/utils.test.js
assertion周りの修正
- `assert.equal` / `assert.deepEqual` => `assert.strictEqual` / `assert.deepStrictEqual` へ修正
- `import assert from "power-assert"`  を  `import assert from "assert"`  へ修正
- babelのpresetが入っているので `power-assert` をimportする必要はないはず。
> fix(test): change to strict mode

- .circleci/config.yml
- https://github.com/greenkeeperio/greenkeeper-lockfile/issues/58 / https://github.com/greenkeeperio/greenkeeper-lockfile/commit/1030eeae9d5858c690ab6f2a83783c7ff3a482b8
によると、_.isEmpty(env.CI_PULL_REQUEST) の判定が狂うのが問題のようなので、そこを無理やり合わせるという修正です
- upload_lock は install の中でやっているので、不要そうに見えたので削除しました
> Try fixing greenkeeper-lockfile-upload

- package-lock.json
- package.json
- src/server/index.js
- src/server/middlewares/apiGateway.js
- src/server/middlewares/reduxApp.js
- src/server/middlewares/requestAdapter.js
- src/server/services/AccessToken.js
- src/server/services/AgreedSample.js
- src/server/services/utils.js
- src/shared/components/organisms/Login/LoginForm.js
- src/shared/components/organisms/Login/index.js
- src/shared/components/organisms/SearchForm/SearchForm.js
- src/shared/redux/modules/csrf.js
- src/shared/redux/modules/reducer.js
SSRであることをフルに活かして、 JavaScript がクライアントで動かなくてもformとしてはGET/POSTができて、実行でき、動作するようにserverサイド側の実装の修正とHTMLの実装修正を行った。
具体的には、 POST/GETをする際にはformのmethodを書くことと、リクエストを生でも受け付けてserviceが動くように修正した。
後ほどデモする。
また、新しいlibraryとして、 is-redirectable-url を追加した。これは、 server 側でopen redirector の脆弱性を突かれないようにするためのモジュールで、任意の場所にredirectしないようにするためのもの。
実装が多岐にわたってしまったので、後で口頭で解説後、問題なければマージする。
> JavaScript がダウンロードされず、実行される前の状況でもformだけは動作するようにした。

- .circleci/config.yml
- package-lock.json
- package.json
- greenkeeper-lockfile-update が機能するためには、そのブランチの最初のビルドかつ、最初のジョブである必要がある [*1][] ため、build ジョブを削除して、install で checkout と greenkeeper-lockfile-update を実行するように修正しました
- ドキュメントによると greenkeeper-lockfile-upload は CI としてのチェックが終わった後に実行されるべきなようなので、upload_lock ジョブは各種チェックを require するように変更しました。
- greenkeeper-lockfile-update の中でなぜか `git config user.name ...` などの設定が効かず、コミットが失敗する現象が起きていたため、install ジョブに git user 指定用の環境変数を追加しました。
[*1]: https://github.com/greenkeeperio/greenkeeper-lockfile/blob/v2.4.0/ci-services/circleci.js#L20-L21
> Retry of #102

- src/client/index.js
https://github.com/recruit-tech/redux-pluto/issues/110
原因は初回に `history.replace(history.getCurrentLocation());` することで毎回スクロール位置が[0, 0]に戻されていたために発生。元々page scopeのために、replace, pushの動きを追っているが、同じpathにリクエストを投げるとpage scope上は前回のscopeに戻ってその後再取得されるため、一時的にrenderが発生してしまう問題に対して、historyを無理矢理初回に変更させる事で修正していたが、ここが原因でスクロール回帰が死んでいた。
page scopeを使わずにapp scopeでやるケースのが多いため、スクロール回帰を復活させる。
> fix(client): remove replace current url and add history

- src/server/middlewares/reduxApp.js
SSR時にdoctypeが入っていなかったため、ブラウザのレンダリングモードが後方互換になるのを修正しました。
> fix(reduxApp): add doctype on SSR

- .circleci/config.yml
- `upload_lock` ジョブ内の greenkeeper-lockfile-upload コマンド実行時に `git stash` が実行される場合があり、その際、git のユーザー情報がない場合にエラーとなってしまうため、`upload_lock` ジョブに対しても greenkeeper のユーザー情報を git にセットする、という修正です
参考: #153
> upload_lock ジョブにも greenkeeper の git user 情報をセットする

- src/client/analytics/config/dev.js
- src/client/analytics/config/prod.js
linkInternalFiltersの設定を
`javascript:,mailto:,tel:,r.recruit.co.jp`
であるべきところ、
`javascript:mailto:,tel:,r.recruit.co.jp`
とカンマ区切りが抜け漏れてしまっていたので再度修正。
> linkInternalFiltersの記法に誤りがあったので修正

- src/client/index.js
configStore()　内で isDevToolVisible を参照しようとするも値が取れないため
devtool がうまく設定されなくなっていた不具合を解消致しました。
> redux-devtool が表示されない不具合の解消

- src/server/components/App.js
```
TypeError: styled_components__WEBPACK_IMPORTED_MODULE_3__.injectGlobal is not a function
at Module../src/server/components/App.js (/Users/01012987/Development/redux-pluto/build/server/webpack:/src/server/components/App.js:10:14)
at __webpack_require__ (/Users/01012987/Development/redux-pluto/build/server/webpack:/webpack/bootstrap:25:1)
at Module../src/server/middlewares/reduxApp.js (/Users/01012987/Development/redux-pluto/build/server/main.js:7618:74)
at __webpack_require__ (/Users/01012987/Development/redux-pluto/build/server/webpack:/webpack/bootstrap:25:1)
at Module../src/server/middlewares/index.js (/Users/01012987/Development/redux-pluto/build/server/main.js:7526:67)
at __webpack_require__ (/Users/01012987/Development/redux-pluto/build/server/webpack:/webpack/bootstrap:25:1)
at …
```
> Fix - injectGlobal -> createGlobalStyle

- src/webpack/dev.client.config.js
- src/webpack/prod.client.config.js
production buildでMOCK_BUILD is undefinedになってしまうため。
> fix: undefined mock_build env in prod

- src/server/services/__tests__/AgreedService.read.test.ts
- src/server/services/__tests__/utils.isSafePath.test.ts
- src/server/services/utils.ts
- src/shared/redux/middleware/apiErrorMiddleware.ts
パストラバーサル対策を目的としたpathnameのバリデーションをread(), create()に追加する。
pathnameにpath.normalize()をかけた際、元と異なる文字列となった場合にリクエストを無効化する。  
path.normalize()によって異なる文字列となるpathnameは以下のようなものである。
```javascript
path.normalize('aaa/../bbb/ccc') → 'bbb/ccc'
path.normalize('aaa/./bbb/ccc') → 'aaa/bbb/ccc'
path.normalize('aaa//') → 'aaa/'
path.normalize('//aaa') → '/aaa'
path.normalize('') → '.'
```
リクエストが無効化された際、レスポンスとしては `403 Forbidden` を返す。
> Add isSafePath validation for prevent path traversal

- src/server/services/__tests__/utils.formatPathname.test.ts
- src/server/services/utils.ts
API呼び出し時の不正なパス操作対策として、安全にpathnameへパラメータを埋め込む関数formatPathnameを追加する。  
SQLのプレースホルダと似た使用感となるようにしている。
formatPathnameは2つの引数を取る。
- pathname: pathnameのテンプレート
- params: パラメータ配列
```javascript
function formatPathname(pathname: string, params: Array<any>): string
```
pathname中に `?` を含めると、その部分がプレースホルダとして扱われる。  
paramsにはプレースホルダを置き換えるデータを指定する。
```javascript
formatPathname("/foo/?/bar/?", [1001, "hoge"]) → "/foo/1001/bar/hoge"
```
内部的にパラメータへencodeURIComponentをかけているので、基本的に記号はURIエンコードされる。
```javascript
formatPathname("/foo/?/bar/?", ["@#$", "../../../hoge"]) → "/foo/%40%23%24/bar/..%2F..%2F..%2Fhoge"
```
ただし、encodeURIComponentは `.`  をエンコードしないため、パラメータが `.` と `..` のときはパス構造が壊れないように別途URLエンコードする。
```javascript
formatPathname("/foo/?/bar/?", [".", ".."]) → "/foo/%2E/bar/%2E%2E"
```
エラーメッセージは `!(MESSAGE)` …
> Add formatPathname function for prevent path manipulation

- .circleci/config.yml
- package-lock.json
直近(2019-04-dd以降)で、 build-assets タスクでCIが失敗することが多くなっていた。
原因はいずれも、brotliの処理でセグフォが発生したことによるもの。
そこで以下の対応を実施。
* circleci/nodeのバージョン10から11に変更
* brotliをnode標準で動かしたかったため(メモリの使用量を減らしたいという狙い)
* moduleの重複を削除(npm dedupeの実施)
* ilbtorbのバージョンが混在していたので
* 古いバージョンにメモリの扱いに問題があり最新の2.4.1で改善の動きがあったため、そちらにバージョンを揃えたかった
* cf. https://github.com/MayhemYDG/iltorb/issues/82
> refactor: CIの安定化

- .circleci/config.yml
直近で `npm audit` が原因でCIが失敗することが多く発生している。
脆弱性の検知はGitHubが提供する[Security Alerts](https://help.github.com/en/articles/about-security-alerts-for-vulnerable-dependencies#githubs-security-alerts-for-vulnerable-dependencies)で検知できる且つ、Greenkeeperでパッチの自動更新ができるためCI上での `npm audit` の実行は廃止したいです。
> chore: Remove "npm audit" job

- package.json
#301 で言及されて居るように react-router を 3 で止めているためその type 定義も greenkeeper で扱わないようにする設定です.
> @types/react-router を greenkeeper の ignore に追加

- package-lock.json
当てれるだけの patch を当てました。
node-codacy-coverage の脆弱性だけ解消できていません。 ( リポジトリがアーカイブされているため )
別の issue として、 coverage の取得を取りやめるか、coverage の取得方法を変更したほうが良いかもしれません。
```
=== npm audit security report ===
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution …
```
> fix security vullnerability
