recruit-tech/redux-pluto

package.json
yarn.lock

refs #62 
- husky を削除して commit 前に lint が走らないように

chore: remove husky

---

.circleci/config.yml
.eslintrc
.sonarishrc.json
package.json
src/server/components/App.js
src/shared/redux/__tests__/agreedSample.test.js
src/shared/redux/analytics/options.js
src/shared/redux/modules/__tests__/alert.test.js
src/shared/redux/modules/__tests__/loading.test.js
src/shared/routes/createUniversalComponent.js
yarn.lock

Install sonarish

---

.jscsrc

prettier 導入でもはや使っていないようなので削除しました

removed `.jscsrc`

---

src/shared/redux/__tests__/counter.test.js
src/shared/redux/__tests__/hackerNews.test.js
src/shared/redux/__tests__/search.test.js
src/shared/redux/__tests__/searchList.test.js
src/shared/redux/__tests__/uploadSample.test.js
src/shared/redux/modules/hackerNews.js
src/shared/redux/modules/reducer.js
src/shared/redux/modules/search.js
src/shared/redux/modules/searchList.js

coverageを上げる

---

src/server/middlewares/offloadDetector.js

- close #81 
他のexpress middlewareもanyを使っていたので、$FIXMEをanyにした

express middleware: $FIXME to any

---

package-lock.json
package.json

- .test.js や __test__/**/*.js は coverage を測る必要がないので ignore しました

fix: ignore test code from coverage

---

src/shared/redux/__tests__/hackerNews.test.js
src/shared/redux/__tests__/search.test.js
src/shared/redux/__tests__/searchList.test.js

failさせるテストでfailしなかった場合通ってしまうテストをfix

---

package-lock.json
package.json
src/__tests__/setups.js
src/shared/components/atoms/Indicator.js
src/shared/components/atoms/SearchListItem.js
src/shared/components/atoms/__tests__/Indicator.test.js
src/shared/components/atoms/__tests__/Menu.test.js
src/shared/components/atoms/__tests__/MenuItem.test.js
src/shared/components/atoms/__tests__/Overlay.test.js
src/shared/components/atoms/__tests__/SearchListItem.test.js
src/shared/components/atoms/__tests__/SearchMore.test.js

atom component の unit test を追加

---

package.json

coverageの範囲修正

---

bin/start-server.js

Tapable.pluginのwarningを消した

---

package-lock.json
package.json

- flow-bin を最新にしても flow check が通るようだったので greenkeeper の ignore から外して最新にするという修正です

flow-bin を greenkeeper の ignore から外す

---

package-lock.json
package.json
src/server/services/__tests__/AgreedSample.read.test.js
src/server/services/utils.js
src/shared/components/organisms/AgreedSample/index.js
src/shared/components/organisms/UploadSample/UploadSample.js
src/shared/components/organisms/UploadSample/index.js
src/shared/redux/__tests__/agreedSample.test.js
src/shared/redux/__tests__/fixtures/hello.txt
src/shared/redux/__tests__/lib/serverUtils.js
src/shared/redux/__tests__/lib/storeUtils.js
src/shared/redux/__tests__/uploadSample.test.js
src/shared/redux/createStore.js
src/shared/redux/middleware/uploader.js
src/shared/redux/modules/reducer.js
src/shared/redux/modules/uploadSample.js

feat(upload): Show image when upload images

---

package-lock.json
package.json

- package.jsonのreactのversionも上げてしまうかどうか。つまり、lock fileだけ上げるか、本体fileも上げてしまうか。
- react dom の version も上げる？
- close #118

update: react v16.4.1  to v16.4.2

---

package-lock.json
package.json
src/shared/components/organisms/UploadSample/UploadSample.js
src/shared/components/organisms/UploadSample/index.js
src/shared/redux/modules/uploadSample.js

WIP feat: image upload cancel

---

flow-typed/redux-effects-steps.js

fix redux-effects-steps flow type

---

src/shared/components/templates/DefaultLayout.js

クラスセレクタが残ってしまっており、スタイルが当たらなくなってしまっていた不具合を修正いたしました。

IndicatorContainer にスタイルが当たっていない不具合の修正

---

src/shared/redux/createStore.js

fix: redux devTools extensionを利用できるようにする

---

package-lock.json
package.json
src/webpack/dev.client.config.js
src/webpack/dev.server.config.js
src/webpack/prod.client.config.js
src/webpack/prod.server.config.js

これがないとstyled-componentsのハッシュが一致しない
babel には入っていたが、ts化した際に外れてしまっていた

Transform styled-components with plugin

---

src/declarations/redux-effects-steps.d.ts
src/shared/redux/__tests__/counter.test.ts
src/shared/redux/modules/agreedSample.ts
src/shared/redux/modules/counter.ts
src/shared/redux/modules/masters.ts
src/shared/redux/modules/search.ts
src/shared/redux/modules/searchList.ts
src/shared/redux/modules/style.ts

redux-actions やめたい。そのたたき台。
とにかく冗長になってもいいので全部書く。
ただこのままやるのは厳しいので、hard-reducer か typescript-fsa を導入したい 。
redux-effects-steps をもうちょっとどうにかできる気がするが…

Typesafe reducer

---

src/webpack/dev.client.config.js
src/webpack/dev.server.config.js
src/webpack/prod.client.config.js
src/webpack/prod.server.config.js

`npm run fix` でerrorが発生していたため。

fix: Fix lint

---

src/shared/redux/modules/agreedSample.ts

よりよい推論のために agreedsample から redux-actionsを 抜いた。
この作業を他のreducer 適用したい @dorayakikun

Drop redux-actions from reducer

---

src/server/services/AgreedSample.ts
src/server/services/BaseMaster.ts
src/server/services/BaseService.ts
src/server/services/__tests__/AgreedService.read.test.ts
src/server/services/utils.ts

axiosにFetchrのheaders情報を `pass through` するようにしました。

refactor: Add headers to axios

---

.circleci/config.yml

chore(circleci): remove upload_lock job

---

package-lock.json
package.json

refactor: Remove react-redux-analytics

---

package-lock.json
package.json
spec/agreed/agreed.ts
spec/agreed/agreedsample/get.ts
spec/agreed/uploadsample/post.ts
src/shared/components/organisms/Footer/index.tsx

agreed OSS modules becomes monorepo.
https://github.com/recruit-tech/agreed/pull/26
this PR upgrades agreed cli tools to @agreed tools

fix: agreed to @agreed

---

package-lock.json

fix handlebars version
